name: CI - Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/syyrynesdyry@gmail.com
        with:
          username: ${{ secrets.SIRINESDIRI }}
          password: ${{ secrets.sirinesdiripassword }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.sirinesdiri }}/instagram-clone:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.sirinesdiri }}/instagram-clone:latest
        run: docker tag instagram-clone ${{ secrets.DOCKER_USERNAME }}/instagram-clone:latest

      # 5. Push vers Docker Hub
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/instagram-clone:latest
